# Generated by Django 4.1.7 on 2023-04-06 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_options_alter_coursecategory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Instructor',
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name_plural': '1. Instructors'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='teacher',
            new_name='instructor',
        ),
    ]
