# Generated by Django 4.1.7 on 2023-04-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_teacher_instructor_alter_instructor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='address',
        ),
    ]
