# Generated by Django 4.1.7 on 2023-04-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_instructor_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='instructor',
            name='mobile_no',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
