# Generated by Django 4.1.7 on 2023-04-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_instructor_mobile_number_instructor_mobile_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='mobile_no',
            new_name='mobile_number',
        ),
    ]
