# Generated by Django 4.1.7 on 2023-04-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_course_course_image_course_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='mobile_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
