# Generated by Django 4.1.7 on 2023-04-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_studentcourseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='login_via_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='login_via_otp',
            field=models.BooleanField(default=False),
        ),
    ]
