# Generated by Django 4.1.7 on 2023-04-19 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_instructor_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='instructor_profile_imgs/', validators=[django.core.validators.FileExtensionValidator(['jpg'])]),
        ),
    ]
