# Generated by Django 4.1.7 on 2023-04-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_instructor_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='student_profile_imgs/'),
        ),
    ]
