# Generated by Django 4.1.7 on 2023-04-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_student_address_student_mobile_number_assignments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentresponse',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignmentSubmissions', to='main.assignments'),
        ),
    ]
